name: dataPy_torch
dependencies:
  - python=3.9
  - ipython
  - jupyter
  - joblib
  - matplotlib
  - networkx
  - numpy
  - pandas
  - pip
  - pip:
    - av
    - click
    - h5py
    - ipywidgets
    - opencv-python
    - timewizard
    - torch==2.0.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
    - torchvision==0.15.2+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
    - tqdm
    - vidio
    - yaml
    - git+https://github.com/dattalab-6-cam/multicam-calibration
    - git+https://github.com/dattalab-6-cam/o2-utils
    - git+https://github.com/calebweinreb/gimbal
    - git+https://github.com/calebweinreb/dynamax.git@parallel_hmm_posterior_sample
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - statsmodels
