name: dataPy_torch
dependencies:
  - python=3.9
  - ipython
  - jupyter
  - joblib
  - matplotlib
  - numpy
  - pandas
  - pip:
    - av
    - click
    - ipywidgets
    - timewizard
    - torch==2.0.1+cu117
    - torchvision==0.15.2+cu117
    - git+https://github.com/dattalab-6-cam/multicamera_keypoints/tree/main
    - git+https://github.com/dattalab-6-cam/multicam-calibration
    - git+https://github.com/dattalab-6-cam/o2-utils
    - git+https://github.com/calebweinreb/gimbal
    - git+https://github.com/calebweinreb/dynamax/tree/parallel_hmm_posterior_sample
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - statsmodels