name: dataPy_torch
dependencies:
  - python=3.10
  - ipython
  - jupyter
  - joblib
  - matplotlib
  - networkx
  - numpy
  - pandas
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - av
    - click
    - h5py
    - imageio-ffmpeg
    - ipywidgets
    - jax[cuda12]<=0.4.14  # Hoping this limits to cuda 12.1: https://docs.nvidia.com/deeplearning/frameworks/jax-release-notes/rel-23-08.html
    - opencv-python
    - optax
    - chex
    - PyYAML
    - timewizard
    - torch  # aiming for cuda 12.1
    - torchvision
    - tqdm
    - vidio
    # - git+ssh://git@github.com/dattalab-6-cam/multicam-calibration
    # - git+ssh://git@github.com/dattalab-6-cam/o2-utils
    # - git+ssh://git@github.com/calebweinreb/gimbal
    # - git+ssh://git@github.com/calebweinreb/dynamax.git@parallel_hmm_posterior_sample
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
